import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_task/src/resources/CommonColor.dart';
import 'package:flutter_task/src/resources/Dimen.dart';

Widget EditTextBorder({
  Color txtColor = CommonColor.txtColorDark,
  Color hintColor = CommonColor.txtColorGray,
  Color cursorColor = CommonColor.gray,
  Color borderColor = CommonColor.borderColorGray,
  TextInputType inputType = TextInputType.text,
  TextInputAction inputTypeAction = TextInputAction.done,
  bool autoFocus = false,
  double txtSize = Dimen.txtSize13px,
  TextCapitalization textCapitalize = TextCapitalization.sentences,
  TextEditingController controller,
  ValueChanged<String> onSubmitted,
  ValueChanged<String> onChanged,
  Widget suffixIcon = null,
  Widget prefixIcon = null,
  FocusNode focus,
  List<TextInputFormatter> formatters,
  EdgeInsetsGeometry margin = const EdgeInsets.fromLTRB(0, 0, 0, 0),
  EdgeInsetsGeometry contentPadding = const EdgeInsets.all(10),
  TextAlign align = TextAlign.start,
  double cornerRadius = 2,
  double cardCornerRadius=2,
  double elevation = 1,
  int minLines = 1,
  int maxlength = 1000,
  String prefixText = null,
  Color bgColor = CommonColor.sfaBgColor,
  String hint = '',
  double cursorWidth = 1,
  VoidCallback onClick,
  bool obscureText = false,
  bool clickableOnly = false,
}) {
  return Card(
    margin: margin,
    color: bgColor,
    elevation: elevation,
    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(cardCornerRadius)),
    child: TextField(
      controller: controller != null ? controller : TextEditingController(),
      keyboardType: inputType,
      textInputAction: inputTypeAction,
      autofocus: autoFocus,
      textAlign: align,
      obscureText: obscureText,
      focusNode: focus != null ? focus : new FocusNode(),
      decoration: InputDecoration(
        suffixIcon: suffixIcon,
        prefixIcon: prefixIcon,
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(cornerRadius),
          borderSide: BorderSide(color: borderColor),
        ),
        focusedBorder: OutlineInputBorder(
          borderSide: BorderSide(color: borderColor),
          borderRadius: BorderRadius.circular(cornerRadius),
        ),
        contentPadding: contentPadding,
        counterText: '',
        hintText: hint,
        hintStyle: TextStyle(
          color: hintColor,
          fontSize: txtSize,
          fontFamily: 'sfaFont',
        ),
      ),
      cursorColor: cursorColor,
      cursorWidth: cursorWidth,
      enableInteractiveSelection: true,
      style: TextStyle(
        color: txtColor,
        fontSize: txtSize,
        fontFamily: 'sfaFont',
      ),
      textCapitalization: textCapitalize,
      onSubmitted: onSubmitted,
      onChanged: onChanged,
      maxLength: maxlength,
      inputFormatters: formatters != null ? formatters : [],
      minLines: minLines,
      maxLines: minLines,
      onTap: onClick,
      readOnly: clickableOnly,
    ),
  );
}
